@host = localhost:8080

### GET /
GET http://{{host}}/
###

### GET index page
GET http://{{host}}/index.html
###

### GET /css/styles.css
GET http://{{host}}/css/styles.css
###

### GET /login?account=gugu&password=password
GET http://{{host}}/login?account=gugu&password=password
###


## POST /register
POST http://{{host}}/register
Content-Type: application/x-www-form-urlencoded

account=wef &
email=wefr@gsadf.com &
password=ef
